#!/usr/bin/env python3
"""
m5r3_export_merged_ply.py

GLIM の dump directory (000000/ ... NNNNNN/) を読み、各 submap の
points_compact.bin を T_world_origin で world 座標に変換して
単一の PLY に書き出す。

背景:
  - 上流 GLIM (koide3) の現行版は merged PCD を自動出力しない
    (protocol doc §4.2 が想定していた dump.pcd / map.pcd は旧 release の話)。
  - offline_viewer の File > Save > Export Points は、保存確定時に
    "terminate called without an active exception" で abort する
    (2026-07-10 確認)。GUI 経由は使えない。
  - よって B1 計測用の merged 点群はこのスクリプトで生成する。

フォーマット (ファイルサイズ比 1:3:3:6 と data.txt から確定):
  points_compact.bin      float32 x N x 3   (submap ローカル座標)
  normals_compact.bin     float32 x N x 3
  intensities_compact.bin float32 x N x 1
  covs_compact.bin        float32 x N x 6
  data.txt                'T_world_origin:' の次の 4 行が 4x4 行列

使い方:
  python3 scripts/m5r3_export_merged_ply.py \
      docs/m5r-bench-data/2026-07-10-campus-outer-final/glim-out-audit-tli \
      -o docs/m5r-bench-data/2026-07-10-campus-outer-final/glim-out-audit-tli/map.ply

  # 点数を減らす (CloudCompare が重い場合、5cm voxel)
  python3 scripts/m5r3_export_merged_ply.py <dump_dir> -o map.ply --voxel 0.05
"""

import argparse
import re
import sys
from pathlib import Path

import numpy as np


def parse_T_world_origin(data_txt: Path) -> np.ndarray:
    """data.txt から T_world_origin (4x4) を読む。"""
    lines = data_txt.read_text().splitlines()
    for i, line in enumerate(lines):
        if line.strip().startswith("T_world_origin"):
            rows = []
            for j in range(i + 1, i + 5):
                vals = [float(v) for v in lines[j].split()]
                if len(vals) != 4:
                    raise ValueError(f"{data_txt}: 行 {j} が 4 要素でない: {vals}")
                rows.append(vals)
            return np.array(rows, dtype=np.float64)
    raise ValueError(f"{data_txt}: T_world_origin が見つからない")


def load_submap(submap_dir: Path, with_intensity: bool):
    pts_path = submap_dir / "points_compact.bin"
    pts = np.fromfile(pts_path, dtype=np.float32)
    if pts.size % 3 != 0:
        raise ValueError(f"{pts_path}: 要素数 {pts.size} が 3 の倍数でない")
    pts = pts.reshape(-1, 3)

    inten = None
    if with_intensity:
        int_path = submap_dir / "intensities_compact.bin"
        if int_path.exists():
            inten = np.fromfile(int_path, dtype=np.float32)
            if inten.size != pts.shape[0]:
                print(
                    f"  warn: {submap_dir.name} intensity 数 {inten.size} != 点数 "
                    f"{pts.shape[0]}、intensity を捨てます",
                    file=sys.stderr,
                )
                inten = None

    # 非有限値を除去 (LiDAR の無効点)
    finite = np.isfinite(pts).all(axis=1)
    if not finite.all():
        pts = pts[finite]
        if inten is not None:
            inten = inten[finite]

    T = parse_T_world_origin(submap_dir / "data.txt")
    R, t = T[:3, :3], T[:3, 3]
    world = (pts.astype(np.float64) @ R.T + t).astype(np.float32)
    return world, inten


def voxel_downsample(pts, inten, leaf):
    """leaf [m] の voxel 内で最初の 1 点を残す簡易ダウンサンプル。"""
    keys = np.floor(pts / leaf).astype(np.int64)
    # 3 軸を 1 本のキーに畳む
    keys -= keys.min(axis=0)
    mul = np.array([1, keys[:, 0].max() + 1,
                    (keys[:, 0].max() + 1) * (keys[:, 1].max() + 1)], dtype=np.int64)
    flat = keys @ mul
    _, idx = np.unique(flat, return_index=True)
    idx.sort()
    return pts[idx], (inten[idx] if inten is not None else None)


def write_ply(path: Path, pts, inten):
    n = pts.shape[0]
    header = [
        "ply",
        "format binary_little_endian 1.0",
        f"comment generated by m5r3_export_merged_ply.py",
        f"element vertex {n}",
        "property float x",
        "property float y",
        "property float z",
    ]
    if inten is not None:
        header.append("property float intensity")
    header.append("end_header")

    with path.open("wb") as f:
        f.write(("\n".join(header) + "\n").encode("ascii"))
        if inten is None:
            f.write(np.ascontiguousarray(pts, dtype="<f4").tobytes())
        else:
            rec = np.empty((n, 4), dtype="<f4")
            rec[:, :3] = pts
            rec[:, 3] = inten
            f.write(np.ascontiguousarray(rec).tobytes())


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dump_dir", type=Path, help="GLIM dump directory")
    ap.add_argument("-o", "--output", type=Path, required=True, help="出力 PLY パス")
    ap.add_argument("--voxel", type=float, default=None,
                    help="voxel ダウンサンプルの leaf size [m] (省略時は全点)")
    ap.add_argument("--no-intensity", action="store_true",
                    help="intensity を書き出さない")
    args = ap.parse_args()

    submaps = sorted(d for d in args.dump_dir.iterdir()
                     if d.is_dir() and re.fullmatch(r"\d{6}", d.name))
    if not submaps:
        sys.exit(f"error: {args.dump_dir} に submap ディレクトリが無い")

    print(f"submaps: {len(submaps)}")
    all_pts, all_int = [], []
    for i, d in enumerate(submaps):
        pts, inten = load_submap(d, with_intensity=not args.no_intensity)
        all_pts.append(pts)
        if inten is not None:
            all_int.append(inten)
        if (i + 1) % 50 == 0 or i + 1 == len(submaps):
            print(f"  {i+1}/{len(submaps)} loaded", flush=True)

    pts = np.concatenate(all_pts, axis=0)
    inten = np.concatenate(all_int, axis=0) if len(all_int) == len(submaps) else None
    del all_pts, all_int
    print(f"merged points: {pts.shape[0]:,}")
    print(f"bbox min: {pts.min(0)}")
    print(f"bbox max: {pts.max(0)}")

    if args.voxel:
        before = pts.shape[0]
        pts, inten = voxel_downsample(pts, inten, args.voxel)
        print(f"voxel {args.voxel} m: {before:,} -> {pts.shape[0]:,}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    write_ply(args.output, pts, inten)
    size_mb = args.output.stat().st_size / 1e6
    print(f"wrote {args.output} ({size_mb:.1f} MB, {pts.shape[0]:,} points)")


if __name__ == "__main__":
    main()
