#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
#
# M6R-1 (Issue #65): smoke test for rsasaki0109/lidar_localization_ros2 against
# a saved static PCD, using a rosbag2 replay as the LiDAR/IMU source.
#
# What "smoke test" means here (parent plan §5, §6 M6R-1):
#   1. Launch lidar_localization via the upstream lidar_localization.launch.py
#      (a LifecycleNode; the launch file drives configure → active transitions).
#   2. `ros2 bag play` the source bag with --clock so localizer timestamps
#      align with the bag.
#   3. Confirm map -> odom TF is being published (proves initial alignment
#      converged and NDT is producing corrections).
#   4. Confirm /pcl_pose (localizer output) is publishing at ~10 Hz.
#   5. Snapshot /alignment_status once so the failsafe designer (M6R-3) can
#      see the actual field layout.
#
# What it does NOT test:
#   - Runtime performance on live sensors (needs the physical WHILL).
#   - EKF integration (M6R-2).
#   - Nav2 obstacle layer (M6R-4).
#   - End-to-end G1-G3 gates (M6R-5).
#
# Companion doc: docs/ja/plans/2026-06-24-m6r-localization.md §6 M6R-1.
# Once this passes, ADR-0006 gets updated with:
#   * commit SHA of lidar_localization_ros2 pinned in whill_lab.repos
#   * the NDT failure threshold observed here
#   * the /alignment_status field schema
#
# Usage:
#   scripts/m6r_smoke_test.sh <site> <bag-dir> [--use-imu]
#
#     <site>     Name under docs/maps/ (e.g. "campus-half-v3"). The script
#                expects docs/maps/<site>/static.pcd to exist.
#     <bag-dir>  rosbag2 directory to replay (e.g.
#                docs/m5r-bench-data/2026-07-07-campus-half-v3/bag).
#     --use-imu  Enable IMU input to the localizer (default: off, per
#                docs/ja/plans/2026-06-24-m6r-localization.md §3.D). When
#                enabled, /imu is remapped to /imu/data_rep145 (PR #56).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat >&2 <<EOF
Usage: ${0##*/} <site> <bag-dir> [--use-imu]

  <site>     Name under docs/maps/ (script reads docs/maps/<site>/static.pcd).
  <bag-dir>  rosbag2 directory to replay.
  --use-imu  Enable IMU input (default: off per plan §3.D).

Outputs land in docs/m6r-bench-data/<YYYY-MM-DD>-smoke-<site>/:
  * out.log           - localizer + bag-play stdout/stderr
  * tf_map_odom.txt   - tf2_echo snapshots of map -> odom over the run
  * pcl_pose.txt      - /pcl_pose messages recorded during the replay
  * alignment_status.txt - one /alignment_status dump for schema mining
  * run_config.yaml   - localizer parameters used (per-run snapshot)
EOF
  exit 2
}

case "${1:-}" in
  -h|--help) usage ;;
esac
if [[ $# -lt 2 || $# -gt 3 ]]; then
  usage
fi

SITE="$1"
BAG_DIR="$2"
USE_IMU="false"
if [[ $# -eq 3 ]]; then
  if [[ "$3" != "--use-imu" ]]; then
    usage
  fi
  USE_IMU="true"
fi

# --- preflight ---------------------------------------------------------------

MAP_PCD="${REPO_ROOT}/docs/maps/${SITE}/static.pcd"
if [[ ! -f "${MAP_PCD}" ]]; then
  echo "ERROR: map PCD not found: ${MAP_PCD}" >&2
  echo "       Generate it via scripts/m5r_run_dufomap.sh first." >&2
  exit 1
fi

BAG_DIR="$(realpath "${BAG_DIR}")"
if [[ ! -f "${BAG_DIR}/metadata.yaml" ]]; then
  echo "ERROR: not a rosbag2 (no metadata.yaml): ${BAG_DIR}" >&2
  exit 1
fi

if [[ ! -f /opt/ros/humble/setup.bash ]]; then
  echo "ERROR: /opt/ros/humble/setup.bash missing. Install ROS 2 humble." >&2
  exit 1
fi
if [[ ! -f "${REPO_ROOT}/install/setup.bash" ]]; then
  echo "ERROR: install/setup.bash missing. Run: colcon build --packages-up-to lidar_localization_ros2" >&2
  exit 1
fi
# shellcheck disable=SC1091
set +u
source /opt/ros/humble/setup.bash
source "${REPO_ROOT}/install/setup.bash"
set -u
if ! ros2 pkg list 2>/dev/null | grep -q '^lidar_localization_ros2$'; then
  echo "ERROR: lidar_localization_ros2 not visible to ros2. Rebuild?" >&2
  exit 1
fi

# --- output dir --------------------------------------------------------------

STAMP="$(date +%Y-%m-%d)"
OUT_DIR="${REPO_ROOT}/docs/m6r-bench-data/${STAMP}-smoke-${SITE}"
mkdir -p "${OUT_DIR}"
OUT_LOG="${OUT_DIR}/out.log"
TF_LOG="${OUT_DIR}/tf_map_odom.txt"
PCL_LOG="${OUT_DIR}/pcl_pose.txt"
ALIGN_LOG="${OUT_DIR}/alignment_status.txt"
CFG="${OUT_DIR}/run_config.yaml"

# --- per-run config ----------------------------------------------------------
# Cloned from the upstream Velodyne preset with map_path + IMU wiring
# overridden. Written out per run so ADR-0006 has an exact record.
# Note: use_sim_time is set true so the localizer honours the bag's clock
# (bag is played with --clock below).

cat > "${CFG}" <<EOF
# Generated by scripts/m6r_smoke_test.sh (M6R-1)
# Base: src/third_party/lidar_localization_ros2/param/boreas_ndt_velodyne.yaml
# Overrides: map_path, initial_pose, IMU wiring, use_sim_time.
/**:
  ros__parameters:
    use_sim_time: true
    registration_method: NDT_OMP
    score_threshold: 6.0
    ndt_resolution: 1.0
    ndt_step_size: 0.1
    ndt_num_threads: 8
    ndt_max_iterations: 25
    transform_epsilon: 0.01
    voxel_leaf_size: 0.5
    enable_scan_voxel_filter: true
    scan_max_range: 80.0
    scan_min_range: 1.0
    scan_period: 0.1
    cloud_queue_depth: 1
    use_pcd_map: true
    map_path: "${MAP_PCD}"
    # Auto-set initial pose is DISABLED here: when the node auto-sets a
    # pose at activation time, its timestamp comes from wall clock (no
    # /clock published yet), while scans from the bag arrive stamped with
    # bag time (~2026-07-07 UTC, seconds before wall clock). The
    # localizer's "dropping scan stamped X s before the latest initialpose"
    # guard then throws every scan away. We publish /initialpose externally
    # AFTER the bag starts so its stamp is bag time.
    set_initial_pose: false
    use_imu: ${USE_IMU}
    enable_map_odom_tf: true
EOF

echo "==> smoke test: site=${SITE}, bag=${BAG_DIR}, use_imu=${USE_IMU}"
echo "==> outputs:    ${OUT_DIR}/"

# --- publish identity odom -> base_link (background) -------------------------
# The bag's /tf_static provides base_link -> {velodyne, imu_link, camera_link}
# but NOT odom -> base_link (which the M4-R EKF supplies at runtime, not
# during bag replay). Without it, the localizer refuses to publish map -> odom
# and never triggers NDT — this smoke test observed exactly that on 2026-07-08.
# Publishing identity here closes the TF chain: localizer's map -> odom
# then simply equals map -> base_link, and NDT can lock. M6R-2 will replace
# this identity with the live EKF supply.
echo "==> publishing identity odom -> base_link…" | tee -a "${OUT_LOG}"
ros2 run tf2_ros static_transform_publisher \
  --x 0 --y 0 --z 0 --roll 0 --pitch 0 --yaw 0 \
  --frame-id odom --child-frame-id base_link \
  >> "${OUT_LOG}" 2>&1 &
ODOM_TF_PID=$!
sleep 1  # let the static TF hit /tf_static

# --- launch localizer via upstream launch file (background) ------------------
# Using the upstream launch file gives us the LifecycleNode's configure→active
# transitions for free, plus the /cloud→/velodyne_points remap and the
# base_link→velodyne static TF the bag already publishes (we disable the
# launch's own static TF via publish_lidar_tf:=false to avoid double-publish).

LAUNCH_ARGS=(
  "localization_param_dir:=${CFG}"
  "cloud_topic:=/velodyne_points"
  "use_sim_time:=true"
  "publish_lidar_tf:=false"   # bag has /tf_static already
)

if [[ "${USE_IMU}" == "true" ]]; then
  # PR #56: /imu/data_rep145 is the REP-145-corrected accel; the raw
  # /imu/data_raw would break de-skew after the sign flip.
  LAUNCH_ARGS+=("imu_topic:=/imu/data_rep145")
fi

echo "==> starting lidar_localization.launch.py…" | tee -a "${OUT_LOG}"
ros2 launch lidar_localization_ros2 lidar_localization.launch.py \
  "${LAUNCH_ARGS[@]}" \
  >> "${OUT_LOG}" 2>&1 &
LAUNCH_PID=$!

# The lifecycle transitions (unconfigured → inactive → active) fire on
# event handlers in the launch file. Wait long enough for that + the
# NDT map load (37 MB PCD parse takes a few seconds).
sleep 8

# Sanity check: node visible and active?
LIFECYCLE_STATE="$(ros2 lifecycle get /lidar_localization 2>/dev/null || echo unknown)"
echo "==> /lidar_localization lifecycle: ${LIFECYCLE_STATE}" | tee -a "${OUT_LOG}"

# --- record diagnostics (background) -----------------------------------------

echo "==> recording /pcl_pose and /alignment_status…" | tee -a "${OUT_LOG}"
ros2 topic echo --once /alignment_status > "${ALIGN_LOG}" 2>/dev/null &
ALIGN_PID=$!

ros2 topic echo /pcl_pose --field pose > "${PCL_LOG}" 2>>"${OUT_LOG}" &
PCL_PID=$!

# poll map -> odom TF every 2s; write dt-annotated lines
: > "${TF_LOG}"   # truncate to remove any prior-run polling residue
(while true; do
  ts="$(date +%s.%N)"
  out="$(timeout 1 ros2 run tf2_ros tf2_echo map odom 2>/dev/null | head -20 || true)"
  echo "[${ts}] ${out}" >> "${TF_LOG}"
  sleep 2
done) &
TF_PID=$!

# --- play bag ----------------------------------------------------------------

BAG_DUR="$(ros2 bag info "${BAG_DIR}" 2>/dev/null | sed -nE 's/^Duration:\s+([0-9.]+)s.*/\1/p' | head -1)"
BAG_DUR="${BAG_DUR:-300}"
echo "==> replaying bag (${BAG_DUR}s)…" | tee -a "${OUT_LOG}"

ros2 bag play "${BAG_DIR}" --clock >> "${OUT_LOG}" 2>&1 &
PLAY_PID=$!

# Wait for /clock to publish a couple of ticks so sim time is live, then
# send /initialpose. Its stamp is generated by ros2 topic pub against
# whatever clock is active — with the bag now publishing /clock and the
# node subscribing via use_sim_time, this stamp lands in bag-time and the
# localizer's timestamp-guard passes.
sleep 2
echo "==> publishing /initialpose…" | tee -a "${OUT_LOG}"
# ros2 topic pub wants the value dictionary on a single line (its YAML
# parser rejects the multi-line form). Use --spin-time 5 so the publisher
# spends 5 s discovering the subscription before firing; -w 1 alone can
# race the localizer's late subscription attachment. The localizer stamps
# incoming poses with its own this->now() (sim time under use_sim_time),
# so we do not need to override header.stamp here.
set +e  # don't kill the whole run if pub races the localizer
ros2 topic pub --once --spin-time 5 -w 1 /initialpose \
  geometry_msgs/msg/PoseWithCovarianceStamped \
  "{header: {frame_id: 'map'}, pose: {pose: {position: {x: 0.0, y: 0.0, z: 0.0}, orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}}, covariance: [0.25, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0.07, 0, 0, 0, 0, 0, 0, 0.07, 0, 0, 0, 0, 0, 0, 0.07]}}" \
  >> "${OUT_LOG}" 2>&1
INITPOSE_RC=$?
set -e
echo "    initialpose pub rc=${INITPOSE_RC}" | tee -a "${OUT_LOG}"

# Wait for bag playback to finish
wait "${PLAY_PID}" 2>/dev/null || true
PLAY_RC=$?
echo "==> bag play finished (rc=${PLAY_RC})" | tee -a "${OUT_LOG}"

# --- teardown ----------------------------------------------------------------

sleep 2  # let last messages flush
for pid in ${ALIGN_PID} ${PCL_PID} ${TF_PID} ${LAUNCH_PID} ${ODOM_TF_PID}; do
  kill -TERM "${pid}" 2>/dev/null || true
done
# Give the launch group's children a moment to fold, then reap.
sleep 1
pkill -TERM -f lidar_localization_node 2>/dev/null || true
pkill -TERM -f "static_transform_publisher.*odom" 2>/dev/null || true
wait 2>/dev/null || true

# --- summary -----------------------------------------------------------------

PCL_COUNT="$(wc -l < "${PCL_LOG}" 2>/dev/null || echo 0)"
TF_OK="$(grep -c "Translation:" "${TF_LOG}" 2>/dev/null || echo 0)"
ALIGN_HAS="$(if [[ -s "${ALIGN_LOG}" ]]; then echo "yes"; else echo "no"; fi)"

echo ""
echo "==> summary"
echo "    /pcl_pose messages recorded : ${PCL_COUNT}"
echo "    map->odom TF snapshots ok   : ${TF_OK}"
echo "    /alignment_status captured  : ${ALIGN_HAS}  → ${ALIGN_LOG}"
echo "    localizer log               : ${OUT_LOG}"
echo ""
echo "Pass criteria for M6R-1 (parent plan §6 acceptance):"
echo "  * PCL_COUNT >= ${BAG_DUR%.*} (i.e. >=1 Hz over the replay)"
echo "  * TF_OK >= 5 (map -> odom stayed alive over multiple polls)"
echo "  * ALIGN_HAS = yes (localizer emits /alignment_status at all)"
echo ""
echo "Next: dump ${ALIGN_LOG} into docs/ja/m6r-localizer-eval.md for ADR-0006,"
echo "      and diff pass/fail against the same command run with --use-imu."
