#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
#
# M6R-1 (Issue #65): smoke test for rsasaki0109/lidar_localization_ros2 against
# a saved static PCD, using a rosbag2 replay as the LiDAR/IMU source.
#
# What "smoke test" means here (parent plan §5, §6 M6R-1):
#   1. Launch lidar_localization_node with map_path = docs/maps/<site>/static.pcd.
#   2. `ros2 bag play` the source bag with --clock so localizer timestamps
#      align with the bag.
#   3. Confirm map -> odom TF is being published (proves initial alignment
#      converged and NDT is producing corrections).
#   4. Confirm /pcl_pose (localizer output) is publishing at ~10 Hz.
#   5. Snapshot /alignment_status once so the failsafe designer (M6R-3) can
#      see the actual field layout.
#
# What it does NOT test:
#   - Runtime performance on live sensors (needs the physical WHILL).
#   - EKF integration (M6R-2).
#   - Nav2 obstacle layer (M6R-4).
#   - End-to-end G1-G3 gates (M6R-5).
#
# Companion doc: docs/ja/plans/2026-06-24-m6r-localization.md §6 M6R-1.
# Once this passes, ADR-0006 gets updated with:
#   * commit SHA of lidar_localization_ros2 pinned in whill_lab.repos
#   * the NDT failure threshold observed here
#   * the /alignment_status field schema
#
# Usage:
#   scripts/m6r_smoke_test.sh <site> <bag-dir> [--use-imu]
#
#     <site>     Name under docs/maps/ (e.g. "campus-half-v3"). The script
#                expects docs/maps/<site>/static.pcd to exist.
#     <bag-dir>  rosbag2 directory to replay (e.g.
#                docs/m5r-bench-data/2026-07-07-campus-half-v3/bag).
#     --use-imu  Enable IMU input to the localizer (default: off, per
#                docs/ja/plans/2026-06-24-m6r-localization.md §3.D). When
#                enabled, /imu is remapped to /imu/data_rep145 (PR #56).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat >&2 <<EOF
Usage: ${0##*/} <site> <bag-dir> [--use-imu]

  <site>     Name under docs/maps/ (script reads docs/maps/<site>/static.pcd).
  <bag-dir>  rosbag2 directory to replay.
  --use-imu  Enable IMU input (default: off per plan §3.D).

Outputs land in docs/m6r-bench-data/<YYYY-MM-DD>-smoke-<site>/:
  * out.log           - localizer + bag-play stdout/stderr
  * tf_map_odom.txt   - tf2_echo snapshots of map -> odom over the run
  * pcl_pose.txt      - /pcl_pose messages recorded during the replay
  * alignment_status.txt - one /alignment_status dump for schema mining
  * run_config.yaml   - localizer parameters used (per-run snapshot)
EOF
  exit 2
}

case "${1:-}" in
  -h|--help) usage ;;
esac
if [[ $# -lt 2 || $# -gt 3 ]]; then
  usage
fi

SITE="$1"
BAG_DIR="$2"
USE_IMU="false"
if [[ $# -eq 3 ]]; then
  if [[ "$3" != "--use-imu" ]]; then
    usage
  fi
  USE_IMU="true"
fi

# --- preflight ---------------------------------------------------------------

MAP_PCD="${REPO_ROOT}/docs/maps/${SITE}/static.pcd"
if [[ ! -f "${MAP_PCD}" ]]; then
  echo "ERROR: map PCD not found: ${MAP_PCD}" >&2
  echo "       Generate it via scripts/m5r_run_dufomap.sh first." >&2
  exit 1
fi

BAG_DIR="$(realpath "${BAG_DIR}")"
if [[ ! -f "${BAG_DIR}/metadata.yaml" ]]; then
  echo "ERROR: not a rosbag2 (no metadata.yaml): ${BAG_DIR}" >&2
  exit 1
fi

if [[ ! -f "${REPO_ROOT}/install/setup.bash" ]]; then
  echo "ERROR: install/setup.bash missing. Run: colcon build --packages-up-to lidar_localization_ros2" >&2
  exit 1
fi
# shellcheck disable=SC1091
set +u; source "${REPO_ROOT}/install/setup.bash"; set -u
if ! ros2 pkg list 2>/dev/null | grep -q '^lidar_localization_ros2$'; then
  echo "ERROR: lidar_localization_ros2 not visible to ros2. Rebuild?" >&2
  exit 1
fi

# --- output dir --------------------------------------------------------------

STAMP="$(date +%Y-%m-%d)"
OUT_DIR="${REPO_ROOT}/docs/m6r-bench-data/${STAMP}-smoke-${SITE}"
mkdir -p "${OUT_DIR}"
OUT_LOG="${OUT_DIR}/out.log"
TF_LOG="${OUT_DIR}/tf_map_odom.txt"
PCL_LOG="${OUT_DIR}/pcl_pose.txt"
ALIGN_LOG="${OUT_DIR}/alignment_status.txt"
CFG="${OUT_DIR}/run_config.yaml"

# --- per-run config ----------------------------------------------------------
# Cloned from the upstream Velodyne preset with map_path + IMU wiring
# overridden. Written out per run so ADR-0006 has an exact record.

cat > "${CFG}" <<EOF
# Generated by scripts/m6r_smoke_test.sh (M6R-1)
# Base: src/third_party/lidar_localization_ros2/param/boreas_ndt_velodyne.yaml
# Overrides: map_path, initial_pose, IMU wiring.
/**:
  ros__parameters:
    registration_method: NDT_OMP
    score_threshold: 6.0
    ndt_resolution: 1.0
    ndt_step_size: 0.1
    ndt_num_threads: 8
    ndt_max_iterations: 25
    transform_epsilon: 0.01
    voxel_leaf_size: 0.5
    enable_scan_voxel_filter: true
    scan_max_range: 80.0
    scan_min_range: 1.0
    scan_period: 0.1
    cloud_queue_depth: 1
    use_pcd_map: true
    map_path: "${MAP_PCD}"
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: ${USE_IMU}
    enable_map_odom_tf: true
EOF

echo "==> smoke test: site=${SITE}, bag=${BAG_DIR}, use_imu=${USE_IMU}"
echo "==> outputs:    ${OUT_DIR}/"

# --- launch localizer (background) -------------------------------------------

IMU_REMAP=()
if [[ "${USE_IMU}" == "true" ]]; then
  # PR #56: /imu/data_rep145 is the REP-145-corrected accel; the raw
  # /imu/data_raw would break de-skew after the sign flip.
  IMU_REMAP=(--ros-args -r "/imu:=/imu/data_rep145")
fi

echo "==> starting lidar_localization_node…" | tee -a "${OUT_LOG}"
ros2 run lidar_localization_ros2 lidar_localization_node \
  --ros-args --params-file "${CFG}" \
  ${IMU_REMAP[@]+"${IMU_REMAP[@]}"} \
  >> "${OUT_LOG}" 2>&1 &
LOC_PID=$!

# lifecycle nodes need a moment to configure + activate
sleep 3

# --- record diagnostics (background) -----------------------------------------

echo "==> recording /pcl_pose and /alignment_status…" | tee -a "${OUT_LOG}"
ros2 topic echo --once /alignment_status > "${ALIGN_LOG}" 2>/dev/null &
ALIGN_PID=$!

ros2 topic echo /pcl_pose --field pose > "${PCL_LOG}" 2>>"${OUT_LOG}" &
PCL_PID=$!

# poll map -> odom TF every 2s; write dt-annotated lines
(while true; do
  ts="$(date +%s.%N)"
  # tf2_echo is line-buffered — take one snapshot per poll
  out="$(timeout 1 ros2 run tf2_ros tf2_echo map odom 2>/dev/null | head -20 || true)"
  echo "[${ts}] ${out}" >> "${TF_LOG}"
  sleep 2
done) &
TF_PID=$!

# --- play bag ----------------------------------------------------------------

BAG_DUR="$(ros2 bag info "${BAG_DIR}" 2>/dev/null | sed -nE 's/^Duration:\s+([0-9.]+)s.*/\1/p' | head -1)"
BAG_DUR="${BAG_DUR:-300}"
echo "==> replaying bag (${BAG_DUR}s)…" | tee -a "${OUT_LOG}"

ros2 bag play "${BAG_DIR}" --clock >> "${OUT_LOG}" 2>&1
PLAY_RC=$?
echo "==> bag play finished (rc=${PLAY_RC})" | tee -a "${OUT_LOG}"

# --- teardown ----------------------------------------------------------------

sleep 2  # let last messages flush
for pid in ${ALIGN_PID} ${PCL_PID} ${TF_PID} ${LOC_PID}; do
  kill -TERM "${pid}" 2>/dev/null || true
done
wait 2>/dev/null || true

# --- summary -----------------------------------------------------------------

PCL_COUNT="$(wc -l < "${PCL_LOG}" 2>/dev/null || echo 0)"
TF_OK="$(grep -c "Translation:" "${TF_LOG}" 2>/dev/null || echo 0)"
ALIGN_HAS="$(if [[ -s "${ALIGN_LOG}" ]]; then echo "yes"; else echo "no"; fi)"

echo ""
echo "==> summary"
echo "    /pcl_pose messages recorded : ${PCL_COUNT}"
echo "    map->odom TF snapshots ok   : ${TF_OK}"
echo "    /alignment_status captured  : ${ALIGN_HAS}  → ${ALIGN_LOG}"
echo "    localizer log               : ${OUT_LOG}"
echo ""
echo "Pass criteria for M6R-1 (parent plan §6 acceptance):"
echo "  * PCL_COUNT >= ${BAG_DUR%.*} (i.e. ≥1 Hz)"
echo "  * TF_OK >= 5 (map -> odom stayed alive over multiple polls)"
echo "  * ALIGN_HAS = yes (localizer emits /alignment_status at all)"
echo ""
echo "Next: dump ${ALIGN_LOG} into docs/ja/m6r-localizer-eval.md for ADR-0006,"
echo "      and diff pass/fail against the same command run with --use-imu."
